name: google_cloudevents_dart
description: This Dart package provides developers with the tools necessary to easily interact with Google Cloud Events, facilitating the integration of Google Cloud services into Dart and Flutter applications. By abstracting the complexity of event handling, this SDK enables you to subscribe to, manage, and dispatch events from Google Cloud services with minimal effort.
version: 0.0.3
repository: https://github.com/a-wallen/google_cloudevents_dart.git
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.7.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.0
  path: ^1.9.0
  test: ^1.27.0
  very_good_analysis: ^10.0.0
  analyzer: ^8.4.0
  logging: ^1.3.0

dependencies:
  fixnum: ^1.1.0
  protobuf: ^5.0.0
